kind: pipeline
type: kubernetes
name: default

steps:
  - name: Run Load-Test
    image : loadimpact/k6
    ports :
      - '6565:6565'
    commands:
      - docker run -i loadimpact/k6 run <loadscript.js

  trigger :
    event :
    - cron
    cron :
    include:
      - nightly

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}
